### ISSUE TITLE
Hide Field in Details not working

### ISSUE THREAD

**Issue by djbbiz** [cortexrd/Knack-Toolkit-Library#245]
I am using _hf=field1, field2… in a details view and have tried both the labels and the actual field codes to hide the fields but they still appear in the details view. The first record hides them but the subsequent records displays them.

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/64454532/cc093d3b-d0bb-4039-9512-732da8ff96fb)
![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/64454532/ab2aa557-beae-416c-9620-a1e47492260e)

**Comment by cortexrd** [comment]
Hi Dean,

I feel this could be a tough one.
That's not the same app you share with me a while ago, by any chance?

I may need to access the page somehow.  Via the app with a login or directly in the Builder, as you wish.

And when you say
>I am using _hf=field1, field2… in a details view and have tried both the labels and the actual field codes to hide the fields but they still appear in the **details view**.

I guess you meant **List view** (last two words)?

Norm

**Comment by cortexrd** [comment]
Ok, I can reproduce the bug here in my tutorial app.
Will look into this now.
Norm

**Comment by cortexrd** [comment]
Fixed!  
The problem also arose with action links, so I fixed those also.

Try the **Dev** mode.

Will be part of next release.
Norm

**Comment by djbbiz** [comment]
Thanks Norm I will give it another go

Dean

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by djbbiz** [comment]
Still the same.  I can make you a login to check it out

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/64454532/779d3ed8-2da3-4825-8ff7-18a7a3212b1e)

**Comment by cortexrd** [comment]
Dean,

All should be fixed now in **v0.23.8**.

Thanks for reporting.
Sharing your app proved to be very helpful.

Norm

**Comment by djbbiz** [comment]
Thanks Norm all looks fixed now! - Dean
