### ISSUE TITLE
_hc prevents rich text field with a table in from displaying properly

### ISSUE THREAD

**Issue by Deanobeano2** [cortexrd/Knack-Toolkit-Library#372]
Hi

I discovered that apparently the _hc keyword seems to prevent a rich text field with a table in from displaying properly.

No _hc

![No _hc](https://github.com/user-attachments/assets/6048291f-949f-4eba-a0c8-dbe26a75def9)

With _hc

![With _hc](https://github.com/user-attachments/assets/e771feb8-e1e1-44f5-8311-b008431bd8cb)

In our case the 2nd, and last column, doesn't display.

Dean

**Comment by CSWinnall** [comment]
Hi Dean

Could you please post the keyword parameters.

Craig

**Comment by Deanobeano2** [comment]
Hi Craig

 

Thank you for reaching out.

 

The KTL keyword being used is “_hc=Day number of week”.

 

Kind regards

Dean Morrison

General Manager
Excell Cleaning Services Limited

**Comment by CSWinnall** [comment]
Thanks Dean
I'll recreate the setup and see if I can fix the  issue.
Kind regards,

Craig Winnall
07543423538

**Comment by Deanobeano2** [comment]
Hi Craig

 

It it’s of any help, even without the KTL code I encountered “strangle behaviour” with 1 of the long tables in the Rich Text Field in this view “spilling over the top” of the line below. I corrected this with some CSS.

 

Kind regards

Dean Morrison

General Manager
Excell Cleaning Services Limited

**Comment by CSWinnall** [comment]
Hi Dean

I have just fixed this. Norm just needs to review and push the changes.

Craig

**Comment by Deanobeano2** [comment]
Hi Craig

Tried again running KTL v0.28.5 but still seeing the same issue, sorry. 

Kind regards
Dean

⁣Get BlueMail for Android ​

**Comment by CSWinnall** [comment]
Hi Dean

It's not available yet I have to wait for Norm to push the fix.

Craig

**Comment by CSWinnall** [comment]
Hi Dean 

I believe it is now available in beta could you test please.

Craig

**Comment by cortexrd** [comment]
Hey guys,

I just did an official prod release now:  **v0.28.6**.

Enjoy,
Norm

**Comment by CSWinnall** [comment]
Thanks
Kind regards,

Craig Winnall
07543423538

**Comment by Deanobeano2** [comment]
Hi Craig & Norm

The issue appears to be fixed, thank you.

Kind regards 
Dean
